### ISSUE TITLE
Dont console.log everything.

### ISSUE THREAD

**Issue by showierdata9978** [MeowerBots/MeowerBot.js#3]
make callbacks for them instead, and nodejs has a class you should extend called EventEmitter

**Comment by mdwalters** [comment]
what

**Comment by mdwalters** [comment]
@showierdata9978

**Comment by showierdata9978** [comment]
not what i ment fully

https://nodejs.org/api/events.html

**Comment by mdwalters** [comment]
ok

**Comment by mdwalters** [comment]
oh i see now, it should be like this:
```js
onLogin(callback) {
   eventEmitter.on("login", () => {
     callback();
   });
};
```

**Comment by mdwalters** [comment]
but it's confusing for functions like `onPost` and `onMessage`

**Comment by showierdata9978** [comment]
> but it's confusing for functions like `onPost` and `onMessage`

just do this.emit("post")

**Comment by mdwalters** [comment]
ok

**Comment by mdwalters** [comment]
ok i did it, but i can't do onPost because it requires arguments to be sent to the callback

**Comment by mdwalters** [comment]
ok i did it

**Comment by mdwalters** [comment]
how to extend...

**Comment by showierdata9978** [comment]
`export default class Bot extends EventEmmiter`

**Comment by mdwalters** [comment]
ok

**Comment by mdwalters** [comment]
then what?
